[package]
name = "sample_rust"
version = "0.1.0"
authors = ["onio <onio@shinzo.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
